### ISSUE TITLE
React

### ISSUE THREAD

**Issue by Andrew-Casner** [Andrew-Casner/Sportrakker#1]
React needs to be included to this project. React is the chosen for its many features for web apps. The combination of its power and ability to scale makes it a perfect fit for this project. The file structure needs to be laid out in a coherent organized way, separating the front end and back end. The .jsx files will need to be compiled with Webpack. For this issue all boilerplate code needs to be created, allowing us to quickly add new react components and integrate them into our front end without any extra work after the component is written. This issue is a high priority and is blocking all front end development.

**Comment by Andrew-Casner** [comment]
@JasonCyrus If you could take a look at this and start this it would be the best for the project.

**Comment by JasonCyrus** [comment]
Sounds good, can you shoot me the link for the software package your using? thanks

**Comment by Andrew-Casner** [comment]
https://github.com/facebook/react

**Comment by Andrew-Casner** [comment]
The [readme](https://github.com/Andrew-Casner/Sportrakker/blob/develop/README.md) found on the develop branch should contain all the needed steps to contribute and run everything.

**Comment by Andrew-Casner** [comment]
@JasonCyrus [this](http://engineering.kapost.com/2016/01/organizing-large-react-applications/) looks like a really good read and a good idea of how I would like to structure the folders. It would be split into backend and frontend completely. Let me know when you have a chance to read over it. Feel free to put all my backend work into its own file. Also let me know if your having trouble viewing the API routes at all. I don't believe those are set up that well. I need to put in more work on those.

**Comment by Andrew-Casner** [comment]
Also I updated the naming convention for branches, no need to change it on your branch but if you could use it from here on out. It was my fault for not being clear enough in the documentation. No worries!

**Comment by JasonCyrus** [comment]
Oh wow haha my bad

**Comment by Andrew-Casner** [comment]
No worries I wasn't clear enough in the documentation.

**Comment by Andrew-Casner** [comment]
@JasonCyrus Since the develop branch has changed since you forked your branch make sure you run `$ git pull origin develop` before you start any work

**Comment by Andrew-Casner** [comment]
React will not be used, insted we will be using a angular 2 as our frontend build
